#!/bin/sh
set -e
if [ ! -d build ]; then
  mkdir build
fi
cd build
if [ ! -d Asan ]; then
  mkdir Asan
fi
cd Asan
if [ -n "$COMPILER" ]; then
  echo "COMPILER is defined, use it: CXX=$COMPILER"
  export CXX=$COMPILER
fi
if [ -z "$CXX" ]; then
    export CXX=clang++
fi
export CXXFLAGS="$CXXFLAGS -fsanitize=address"
conan install --build=missing ../..
cmake ../.. -GNinja
ninja -v
./bin/run-tests
cd ../..
