#!/bin/sh
set -x
if [ $# -eq 0 ] ; then
  FILES=`git diff  --name-only --diff-filter=AMR '*.cpp' | xargs`
  if [ -z "$FILES" ]; then
    FILES="src/*.cpp test/*.cpp"
  fi
else
  FILES="$1"
fi
echo Checking $FILES
clang-tidy $FILES -config-file='.clang-tidy' -- -std=c++17 -Ivendor/catch/include -Isrc/core

